apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    configmap-operator-key: prom.yaml
    configmap-operator-src: https://raw.githubusercontent.com/prometheus/prometheus/main/documentation/examples/prometheus.yml
  labels:
    app.kubernetes.io/component: kubernetes-operator
    app.kubernetes.io/instance: configmap-operator
    app.kubernetes.io/name: configmap-operator
  name: example-prom-config
  namespace: configmap-operator-demo
