apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-operator
    app.kubernetes.io/instance: configmap-operator
    app.kubernetes.io/name: configmap-operator
  name: configmap-operator-role
  namespace: configmap-operator-demo
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
  - update
